services:

  testK8sSpringBoot:
    image: test-k8s-image:latest
    container_name: testK8sContainer
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

# create Docker image
# docker build --tag=test-k8s-image:latest .
# deploy docker-compose
# docker compose up
# verify
# http://localhost:8080/item